### Input files ###############################################################
INPUT_DATA:
  type: "cellranger"
  path: "/path/to/dir"
  delimiter: ","
  target_name: "target_name"

INPUT_QC_REPORT_RMD_FILE: "Rmd/single_sample/01_input_qc.Rmd"
###############################################################################

### Removal of empty droplets #################################################
EMPTY_DROPLETS_ENABLED: True
EMPTY_DROPLETS_LOWER: 100
EMPTY_DROPLETS_FDR_THRESHOLD: 0.01
###############################################################################

### Cell filtering ############################################################
ENABLE_CELL_FILTERING: True
SAVE_DATASET_SENSITIVE_FILTERING: True
###############################################################################

### Dataset-sensitive cell filtering ##########################################
MAD_THRESHOLD: 3
###############################################################################

### Custom cell filtering #####################################################
MIN_UMI_CF: 1000
MAX_UMI_CF: 50000
MIN_FEATURES: 1000
MAX_MITO_RATIO: 0.2
###############################################################################

### Gene filtering ############################################################
ENABLE_GENE_FILTERING: True

MITO_REGEX: "^MT-"
RIBO_REGEX: "^RP[SL]"

MIN_UMI: 1
MIN_RATIO_CELLS: 0.01
###############################################################################

### Output files ##############################################################
INPUT_QC_BASE_OUT_DIR: "01_input_qc"

INPUT_QC_REPORT_HTML_FILE: "01_input_qc.html"
###############################################################################

### HTML output parameters ####################################################
INPUT_QC_KNITR_MESSAGE: False
INPUT_QC_KNITR_WARNING: False
INPUT_QC_KNITR_ECHO: False
###############################################################################
